### PR TITLE
Prevent duplicate outputs in NemoLite2D PSyKAl DM

### LINKED ISSUE #52: NemoLite2D PSyKAl has duplicate output lines when running with distributed memory.

### PR DESCRIPTION
**Pull request by sergisiso**
Fixes #52 

- [x] This requires dl_esm_inf/47 to be merged first and then update the submodule.
- [ ] Also a PSyclone version with the GOcean DM support in it.

### CODE REVIEW

**Comment by sergisiso** [comment]
Right now I used the get_rank() function in the algorithm layer to prevent duplicate outputs in distributed memory, but I am not sure this is the right thing to do as the algorithm writer has to know about ranks (which is a parallel concept even though it is a function exposed by the infrastructure).

Alternatively I can make the dl_esm_inf 'model_write_log()' functions to internally print only on the master rank, but this will not allow to log from any other rank.

Or I can implement an optional parameter  'model_write_log(format, msg, all_ranks=.true.)' (my preferred option) or a second set of functions 'model_master_write_log()' to be more subtle about what to log?

@rupertford @arporter  @hiker Before I implement any of these on dl_esm_inf, what are your thoughts?

**Comment by hiker** [comment]
I like the optional parameter. This would also give us the flexibility to if some messages might only be written by some processes (just specify all_ranks=.true., and it would be printed). 
Since there is some inflexibility with the write_log functions, you could (additionally) provide a function 'do_output', e.g.:
```
if do_output():
    print *,"Some warning"
```
This would allow to hide the rank test for the application, and push it into the infrastructure.

But I think the first one is the one we (you :) ) need, so no need for anything else atm.

**Comment by rupertford** [comment]
> Or I can implement an optional parameter 'model_write_log(format, msg, all_ranks=.true.)' (my preferred option)

Yes this seems a good idea. Is this exposed at the algorithm layer as well? i.e. the algorithm writer would need to add this? If so, I was wondering whether it might be better to have it as a dl_esm_inf configuration parameter?

**Comment by sergisiso** [comment]
> Yes this seems a good idea. Is this exposed at the algorithm layer as well? i.e. the algorithm writer would need to add this? If so, I was wondering whether it might be better to have it as a dl_esm_inf configuration parameter?

Usually it won't be exposed, as most of the time one expects to write a message just once with `model_write_log(format, msg)`, but for debugging certain values is useful to have the all_ranks option.

Note that the configuration parameter would make all log writes in the application behave in one way or the other, while I was trying to chose for every specific log call.

Maybe a third option is to make the `model_write_log()` write always only in master rank. And for debugging or more specific writes, one have to use a manual `if(get_rank() == 1) write (*,*) msg` expression in the algorithm? but I still prefer the optional parameter more.

**Comment by rupertford** [comment]
> Note that the configuration parameter would make all log writes in the application behave in one way or the other, while I was trying to chose for every specific log call.

Ah yes, good point.

**Comment by sergisiso** [comment]
Closing this PR, these modifications come as part of other branches.

**Pull request closed without merging**
