### PR TITLE
Update dl_esm_inf

### PR DESCRIPTION
**Pull request by sergisiso**
Quick PR without an associated issue with the necessary modifications to update to the last version of dl_esm_inf.

### CODE REVIEW

**Comment by sergisiso** [comment]
@arporter This is ready for review, it brings the recent infrastructures updates to PSycloneBench.

**Comment by arporter** [comment]
Hi @sergisiso - are you able to compile any of the models in `PSycloneBench/benchmarks/nemo/nemolite2d/manual_versions/psykal_serial`? I get an error about mismatched components of a derived type. I expect it's something messed-up on my system but just wanted to double check.

**Comment by sergisiso** [comment]
Yes, I can compile all them (some give different results but also did before these changes).

I assume you made a `make allclean` before? Can you try going to the parent folder (manual_versions) and making an allclean from there?

**Comment by arporter** [comment]
> Yes, I can compile all them (some give different results but also did before these changes).
> 
> I assume you made a `make allclean` before? Can you try going to the parent folder (manual_versions) and making an allclean from there?

I did do `allclean` before. Going up to the parent folder and doing it there fixed it though so I'm happy enough :-)

**Comment by sergisiso** [comment]
I am improving the serial implementations Makefile in https://github.com/stfc/PSycloneBench/compare/fortran_loop_boundaries
I will fix there this issue.

**Pull request merged**
