### PR TITLE
Opencl psykal

### PR DESCRIPTION
**Pull request by arporter**
This PR introduces a new target where PSyclone is used to generate OpenCL (driver) code for NEMOLite2D. The kernels themselves are not touched and must be manually ported to OpenCL. This will be the subject of future work.
I've also repaired the two-kernel, C version as I discovered that it was broken.

### CODE REVIEW

**Comment by arporter** [comment]
@rupertford, I can't remember what we decided to do about code reviews for this repo - do you fell strongly?

**Comment by arporter** [comment]
Requesting a 'light-touch' review, as discussed...

**Comment by arporter** [comment]
The offending code is in what passes for the IO library of PSycloneBench (nemolite2d/common/gocean2d_io_mod.f90). Could we move it into dl_esm_inf instead - how much of it is common with Shallow?

**Comment by arporter** [comment]
The alternative is to implement a getter for the field data which could return a pointer to the data after first making sure that it is up-to-date (i.e. copying it back from the remote device).

**Comment by arporter** [comment]
OK, the problem of dealing with data copying has now been moved into the infrastructure. Note that I've not bothered to go through all the manual PSy-layer code - it still accesses `field%data` directly. That can be something for another issue (if we feel strongly). Back for second review... (Note that Travis is failing because it is unable to clone FortCL. I've just tried cloning it myself and it was fine so I don't know what's going on...)

**Comment by sergisiso** [comment]
I changed the old 'under review' label to 'in progress' as I will update this PR to generate the OpenCL driver and kernel. Also I deleted 'nemolite2d_opencl' and 'opencl_psykal_fix' branches as these are already merged into master or into this PR.

**Comment by sergisiso** [comment]
@arporter I think it is time to merge this to master as it is already larger than I like and the nemolite2d psykal generation works correctly for the different platforms (although not very fast). Note that we have both made changes in this PR, but it seems that the repository allows any of us to review it anyway. It contains:
- Modifications to the OpenCL nemolite2d manual implementations (I not verified them but I am not too worried about them for now)
- Add the ocl_trans.py into the nemolite2d psykal version to enable automatic OpenCL generation.
- Split the Makefile of nemolite2d psykal into code generation and compilation steps. This is useful to maintain multiple working copies of different versions to try multiple things at once (useful for the overnight FPGA compilations)
- Updates dl_esm_inf (and FrotCL) dependencies with the necessary infrastructure to execute the OpenCL

**Pull request merged**
